### ISSUE TITLE
[DSL Training] Prepare Basic Concepts of Unstructured Meshes

### ISSUE THREAD

**Issue by Stagno** [dawn-ico/dusk-dawn-notebook#13]
There is already some material. Reuse/adapt to fit time schedule.

**Comment by BenWeber42** [comment]
I could take this. I think I can reuse quite a lot from the DSL workshop in Oct (last week).

**Comment by Stagno** [comment]
@BenWeber42 sure, go ahead. Just remember to assign to yourself and move the task to In Progress in the board so that everybody is informed :)
