### ISSUE TITLE
[DSL Training] How to handle audience questions?

### ISSUE THREAD

**Issue by BenWeber42** [dawn-ico/dusk-dawn-notebook#30]
* Questions google docs? (if so, prepare google docs)
* Text chat of VC?
* Voice chat of VC?

**Comment by mroethlin** [comment]
* Audience questions during _presentations_ are collected in google docs. Andy will prepare them beforehand (one for each presentation)
*  Audience questions during _hands on sessions_ will be answered in slack (only for MCH sessions).
