### ISSUE TITLE
Open steps towards a clean solution

### ISSUE THREAD

**Issue by BenWeber42** [dawn-ico/dusk-dawn-notebook#4]
An incomplete list of things we should probably address at some point (roughly in order of importance):

- [x] Check launch time of the notebook (check also on days when the notebook has never been launched to emulate a _cold cache_ scenario)
- [x] Try to find out whether mybinder will slow down if many users use the same repo simultaneously -> We can have a maximum of 100 concurrent users. Beyond that we could still request a higher limit for things like workshops.
- [x] Verify whether docker hub pull limits could be a problem (could we also use a different provider?) -> https://discourse.jupyter.org/t/dockerhub-pull-limits-mybinder-org/6381/2 (should be ok, but we'll prepare a backup solution)
- [x] Are there other rate limits that could become problematic? -> Neither mybinder nor dockerhub state other limits (github actions limits should be fine)
- [x] Which docker hub account should we push images to? (do we have a `dawn-ico` docker hub account) -> https://hub.docker.com/u/dawnico
- [x] Use a nightly build of dawn (the current base image isn't built/pushed nightly) -> build is triggered by pushes on master
- [x] Figure out a good way to add the additional dependencies (mostly from the `icondusk-e2e` spack package, should we use spack when building the image?)
- [x] Add proper notebooks to showcase dusk (+exercises)
- [x] Add driver code so that generated cpp files can be run
- [x] Add _exercises_ or demos for users
- [x] Figure out how we can start the lab edition by default and how we can configure the initial lab layout
- [x] Get a _nice_ link for the notebook: https://cutt.ly/dusk-dawn-notebook
- [x] Add way to visualize output fields of exercise/demo stencils
- [x] Add other useful utilities (`clang-format`)
- [x] ~~Should we provide stable versions and nightly versions of the notebook? (if so, how? maybe branches?)~~
- [x] ~~Can we separate the notebook part into a separate image so we provide a docker image of only dawn/dusk + useful dependencies (`icondusk-e2e` stuff)~~

**Comment by elsagermann** [comment]
* [ ]  Check launch time of the notebook (check also on days when the notebook has never been launched to emulate a _cold cache_ scenario)  
> < 1 min if already launched

    * [ ]  Try to find out whether mybinder will slow down if many users use the same repo simultaneously

    * [x]  Verify whether docker hub pull limits could be a problem (could we also use a different provider?)
> Data transfer (per 6 hours):  Authenticated users (Docker ID) | 200 pulls

    * [x]  Are there other rate limits that could become problematic?
> See https://www.docker.com/pricing

    * [ ]  Which docker hub account should we push images to? (do we have a `dawn-ico` docker hub account)
> Is defined by the  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} and DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} of the github action. We can use my acount I don't really care.

    * [ ]  Use a nightly build of dawn (the current base image isn't built/pushed nightly)
> That you have to ask the dawn builders :)

    * [ ]  Figure out a good way to add the additional dependencies (mostly from the `icondusk-e2e` spack package, should we use spack when building the image?)
> Dawn, Atlas Eckit and cie are already in the base image, I don't get this comment.

    * [ ]  Add proper notebooks to showcase dusk (+exercises)

    * [ ]  Add driver code so that generated cpp files can be run

    * [ ]  Add _exercises_ or demos for users

    * [ ]  Figure out how we can start the lab edition by default and how we can configure the initial lab layout
> ?urlpath=lab, [https://mybinder.readthedocs.io/en/latest/sample_repos.html#create-a-binder-link-that-points-to-jupyterlab](https://mybinder.readthedocs.io/en/latest/sample_repos.html#create-a-binder-link-that-points-to-jupyterlab)

    * [ ]  Get a _nice_ link for the notebook

    * [ ]  Add way to visualize output fields of exercise/demo stencils

    * [ ]  Should we provide stable versions and nightly versions of the notebook? (if so, how? maybe branches?)

    * [ ]  Can we separate the notebook part into a separate image so we provide a docker image of only dawn/dusk + useful dependencies (`icondusk-e2e` stuff)
